### PR TITLE
Improve whitespace and search matches colors

### LINKED ISSUE #3: Whitespace characters barely visible
On Helix 23.03, when the option to see whitespace characters is enabled [1], they turn out to be barely visible in rose pine themes. Here’s the output for the moon variant :

| Not selected | Selected |
|------------------- | ------------ |
| image | image |

It would be maybe better to have them colored as comments perhaps?

[1] https://docs.helix-editor.com/configuration.html#editorwhitespace-section

### PR DESCRIPTION
**Pull request by Iorvethe**
# Whitespaces

| Before | After |
|- | - |
| image|image|

# Search matches

| Before | After |
| - | - |
|image | image |

Closes #3

### CODE REVIEW

**Comment by mvllow** [comment]
I love the search change, I thought something looked off when switching between neovim and helix. What if we meet in the middle for the whitespace, maybe `highlight_high`? Seeing how this is an opt-in feature, more contrast via `muted` is fine if you feel it's needed :)

**Comment by Iorvethe** [comment]
You are right, the `highlight_high` is better, since these are way less important than comments and shouldn’t be with the same colors.

As for the search, happy that you like it! Now that I used it a little, I’m thinking of maybe adding an indicator of which line the cursor is on, because it becomes tiresome to always look at the left side to know which result is selected. Especially with long paths spanning half the editor.

What kind of highlight would in you opinion be better suited here? The default theme changes the foreground but other themes appear to be fiddling with the background.

**Comment by mvllow** [comment]
For the current search line background we use `overlay` in other apps :)

**Comment by Iorvethe** [comment]
Okay, added the `ovelay`. It should be good now!

**Pull request merged**
